---
title: "Assignment 3 - Task 3 - Lauren Harris"
author: "Lauren Harris"
date: "10/21/2021"
output: html_document
---
## Setup
```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(here)
library(tidyverse)
library(janitor)
library(kableExtra)
library(lubridate)
```

## Read in data
```{r}
urchins_data <- read_csv(here("data", "urchins.csv"))
```

## Clean up data
```{r}
urchins_clean <- urchins_data %>% 
  clean_names()
```

## Urchin size comparison

### Data visualization
```{r}
# Comparing the sizes of red and purple urchins with a histogram
ggplot(data = urchins_clean, aes(x = size)) +
  geom_histogram(bin_width = 10) +
  facet_wrap(~common_name) +
  labs(x = "Urchin diameter (cm)", y = "Count")
```

Figure caption goes here

### Table
```{r}
urchins_size_subset <- urchins_clean %>% 
  group_by(common_name, scientific_name) %>% 
  summarize(mean_size = mean(size), median_size = median(size), sd_size = sd(size), n_size = n()) 

urchins_size_subset %>% 
  kable(digits = 2, col.names = c("Common Name", "Scientific Name","Mean Size (cm)", "Median Size (cm)", "Standard Deviation", "Sample Size")) %>% 
  kable_styling(full_width = FALSE)
```
2-3 sentences about data spread, distribution, central tendency, etc.

## Purple Urchins analysis
```{r}
purple_urchins <- urchins_clean %>% 
  filter(common_name == "Purple Urchin") %>% 
  mutate(date = mdy(date)) %>% 
  mutate(year = year(date)) %>% 
  mutate(site_full = case_when(site %in% "NAPL" ~"Naples Reef",
         site %in% "AQUE" ~"Arroyo Quemado Reef",
         site %in% "CARP" ~"Carpinteria Reef", 
         site %in% "MOHK" ~"Mohawk Reef",
         site %in% "IVEE" ~"Isla Vista Reef"))

```

